language: node_js

node_js:
  - "12"

addons:
  chrome: stable

services:
  - xvfb

install:
  - yarn install
script:
  - yarn test:ci
after_success:
  - yarn test:report

notifications:
  webhooks:
    urls:
      - https://coveralls.io/webhook
