name: Node CI with NPM

on: [push, pull_request, workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: 12.x

    - name: Cache node modules
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

    - name: Install Chrome drivers
      run: sudo apt-get install xvfb

    - name: Install dependencies
      run: yarn install

    - name: Test CI
      run: xvfb-run --auto-servernum yarn test:ci

    - name: Coveralls coverage report
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ./coverage/scholars-angular/lcov.info
